services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: doctofree
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    volumes:
      - manu_doctofree_database:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  manu_doctofree_database:
